
# -----------  Agents  -----------


[[agents]]
id = "test_agent2"
name = "Agent 2"
public_address = "HcSCjh3PO76Cmtiy3zjCzCZmDz34zf36eD6swweHfuiquca7ZfJv7W9w7TXbksi"
keystore_file = "./key2.keystore"

# -----------  DNA  -----------


[[dnas]]
id = "holoster_dna"
file = "./dna/holoster.dna.json"
hash = "QmcG15xmejBHSnh8FeQapXBwVqys5McL6ugYMr3nadws6j"

[[instances]]
id = "holoster_instance"
dna = "holoster_dna"
agent = "test_agent2"
#[instances.logger]
#type = "simple"
#file = "app_spec2.log"
[instances.storage]
type = "file"
path = "./tmp-storage2"


[[interfaces]]
id = "holoster_http_interface"
[interfaces.driver]
type = "http"
port = 8889
[[interfaces.instances]]
id = "holoster_instance"

# -----------  UI  -----------

#[[ui_bundles]]
#id = "main"
#root_dir = "./ui"
#hash = "Qm000"

#[[ui_interfaces]]
#id = "ui-interface"
#bundle = "main"
#port = 4201
#dna_interface = "holoster_http_interface"

# -----------  Networking  -----------

 [network]
 n3h_persistence_path = "/tmp/n3h/2"
 bootstrap_nodes = ["wss://192.168.43.152:38719/?a=HcScjxEfwTPe8zb9d9r5zrZ3AW4wVzz7rXq6zsukv7AyayeaqDMyAGeumepsi3r"]

# -----------  Networking instructions  -----------

# To get networking running requires the following steps:

# - Clone the repo for the holochain networking library n3h (https://github.com/holochain/n3h)
# - Checkout the tag in n3h for holochain v0.0.4-alpha (git fetch --tags && git checkout v0.0.4-alpha)
# - run `npm install && npm run boostrap` in the n3h directory
# - change the n3h_path below to point to the location where you cloned the repo

# - If you are the first node then start the conductor and take careful note of the line that
#	begins with `READY! tcp://127.0.0.1:43859 [...]
#	You will need to copy the contents of the array and send it to the nodes you plan to network with.
# - If you are a joining node then paste the contents from the first node in to the bootstrap_nodes field above
# - Make sure that you all have different agents for your instances (uncomment new agent and change the instances agent field)
# - Uncomment the network section and you should be ready do go!
